---
title: "R Notebook"
output: html_notebook
---


```{r packages}
library(ggplot2)
library(tidyverse)
library(brms)
library(beepr)
library(here)
library(tidybayes)
library(lme4)
library(broom)
library(modelr)
```




# Model


## most current code


```{r mod_DOY_binomial}
#rm(mod.1)
mod.wild_chinook_doy <- brm(alive | trials(n) ~ doyz + I(doyz^2) + transport + doyz:transport + I(doyz^2):transport + (1 + doyz + I(doyz^2) + transport | year), 
                   data = df.agg, 
                   family = binomial(link = "logit"), 
                   chains = 3,
                   cores = 3,
                   file = here("Examples/results", "mod_wild_chinook_doy")
                   )
summary(mod.wild_chinook_doy)
#mod.3 rerun with year as factor--no change
```

```{r mod_TEMP_binomial}
rm(mod_hatchery_chinook_temp)
mod_hatchery_chinook_temp <- brm(alive | trials(n) ~ mean.tempz + I(mean.tempz^2) + transport + mean.tempz:transport + I(mean.tempz^2):transport + (1 + mean.tempz + I(mean.tempz^2) + transport | year), 
                   data = df.agg, 
                   family = binomial(link = "logit"), 
                   chains = 3,
                   cores = 3,
                   file = here("Examples/results", "mod_hatchery_chinook_temp")
                   )
summary(mod_wild_chinook_temp)
#mod.3 rerun with year as factor--no change
mod_hatchery_chinook_temp$data

```
