---
title: "Map"
output: html_document
date: "2023-12-28"
---


```{r}
library(rnaturalearth)
```


```{r}
xlim <- c(-125, -115)
ylim <- c(45, 49)


library(rnaturalearth)
library(rnaturalearthdata)
library(ggplot2)
library(sf)

# Load world map data
us_states <- ne_states(country = "United States of America", returnclass = "sf")


# Filter PNW states (Washington, Oregon, Idaho)
pnw_states <- us_states%>%
  filter(admin == "United States of America" &
           name %in% c("Washington", "Oregon", "Idaho"))

# Get centroids of PNW states for labeling
pnw_state_centroids <- st_centroid(pnw_states)

# Define bounding box for PNW states
pnw_bbox <- st_bbox(pnw_states)


# # Load Columbia River data
# columbia_river <- ne_rivers_lake_centerlines(scale = "medium", returnclass = "sf") %>%
#   filter(name == "Columbia")

# Define locations for Bonneville Dam and Lower Granite Dam
dam_locations <- data.frame(
  name = c("Bonneville Dam", "Lower Granite Dam"),
  lon = c(-121.9524, -117.42806),  # Longitude for Bonneville and Lower Granite Dams
  lat = c(45.6387, 46.66056)  # Latitude for Bonneville and Lower Granite Dams
)

dam_locations <- st_as_sf(dam_locations, coords = c("lon", "lat"), crs = 4326)


rivers50 <- ne_download(
  scale = 50,
  type = "rivers_lake_centerlines",
  category = "physical",
  returnclass = "sf"
) %>% 
  filter(name %in% c("Columbia", "Snake"))

river_dam_labels <- data.frame(
  name = c("Snake River", "Columbia River", "Bonneville Dam", "Lower Granite Dam"),
  lon = c(-117.293, -120, -121.953, -117.42806),  # Longitude for the rivers and dams
  lat = c(45.5, 45.6, 45.8, 46.8)  # Latitude for the rivers and dams
)
(river_dam_labels <- st_as_sf(river_dam_labels, coords = c("lat", "lon"), 
    crs = 4326, agr = "constant"))


# Plot only PNW states
ggplot() +
  geom_sf(data = us_states, fill = "grey", color = "black") +
  geom_sf(data = rivers50, color = "darkblue", size = 1) +
  geom_sf(data = dam_locations, 
          aes(geometry = geometry), 
          fill = "black", 
          size = 3, 
          shape = 21) +
  geom_text(data = pnw_state_centroids, 
            aes( x = longitude, y = latitude, label = name), 
            size = 3, 
            fontface = "bold", 
            color = "black") +
  geom_text(data = filter(river_dam_labels, name %in% c("Snake River", "Columbia River")), 
            aes(x = lon, y = lat, label = name), 
            size = 3,  
            color = "darkblue") +
    geom_text(data = filter(river_dam_labels, name %in% c("Bonneville Dam", "Lower Granite Dam")), 
              aes(x = lon, y = lat, label = name), 
              size = 3, 
              color = "black") +
  labs(title = "Pacific Northwest States Map with Columbia River and Dams") +
  theme_minimal() +
  theme(legend.position = "none")+
      coord_sf(xlim = xlim, ylim = ylim, expand = FALSE)

  # coord_sf(xlim = c(pnw_bbox$xmin, pnw_bbox$xmax),
  #          ylim = c(pnw_bbox$ymin, pnw_bbox$ymax),
  #          expand = FALSE) 

  # labs(title = "Pacific Northwest States Map")

?rnaturalearth()
```

